import sklearn.mixture as mixtures
from itertools import product
import pdb


def create_models(X, Y):
    """ X and Y are, respectively, the input and output vectors """
    nmodel = 1
    for model in _modelers_generator(X, Y):
        print('Running modelers {}'.format(nmodel), end='\r')
        nmodel += 1
    return Modeler(best_model)


def _map_adaptation():
    pass


def _modelers_generator(X, y):
    qtd_components = [x for x in range(1, 10, 1)]
    covariances = ['full', 'tied', 'diag', 'spherical']
    tol = [0.01, 0.001, 0.0001]
    grid = product(qtd_components, covariances, tol)
    for row in grid:
        gmm = mixtures.GaussianMixture(n_components=row[0],
                                       covariance_type=row[1], tol=row[2])
        gmm.fit(X)
        yield gmm


class Modeler:

    def __init__(self, model):
        self.model = model

    def likelihood(self, Xi, speaker_id):
        """ Return the log-likelihood that the vector Xi is generated by
        speaker_id """
        probabilities = self.model.predict_proba(Xi)
        return probabilities[speaker_id]

    def validate(self, Xi, speaker_id, threshold=0.9):
        """ """
        if threshold <= 0.0 or threshold >= 1.0:
            raise ValueError('threshold must be in [0.0, 1.0]')
        acceptance = self.predict_proba(Xi)
        return acceptance >= threshold
